<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rejection Based Retrying</title>
</head>

<body>

</body>

</html>
<script>
    const wait = (ms) => new Promise((res) => setTimeout(res, ms));

    function info(depth, wait) {
        this.depth = depth;
        this.wait = wait;
    }

    const maybeFail = (successProbability, result, error) => new Promise((res, rej) => Math.random() < successProbability ? res(result) : rej());

    const maybeFailingOperation = async() => {
        await wait(10);
        return maybeFail(0.1, "result", "error");
    }


    const callWithRetry = async(fn, depth = 0) => {
        const table = new info(depth, (2 ** depth * 10));
        console.table(table);
        try {
            return await fn();
        } catch (e) {
            if (depth > 7) {
                throw e;
            }
            await wait(2 ** depth * 10);
            return callWithRetry(fn, depth + 1);
        }
    }

    const run = async() => {
        const result = await callWithRetry(maybeFailingOperation);
        console.log("finish")
    };
    run()
</script>